NEKO_GIFS = [
    
      "CgACAgEAAxkBAAIMqWKkwJl_fnKO6mJTiQVgKj0SS41vAAKfAQACBD4xROyqx6xIce5YJAQ",

"CgACAgQAAxkBAAIMrGKkwMB_blD-bNvnheVCEgQSf_ncAAJWBwACKUn5UER8Oc82sIHyJAQ",

"CgACAgQAAxkBAAIMr2KkwPtvMAwMQr7aiZVC5vQSMphcAAIFCQACaPH4U3H6blRPTuNcJAQ",

"CgACAgQAAxkBAAIMsmKkwREX5mjlpb_Y7TcukoFVFqF5AAIRCQACqz7BUUTXqxHDXu29JAQ",

"CgACAgQAAxkBAAIMtWKkwSpbTQAB7dO7rX2aUThycvHLZgACKQwAAh2eiVH4QOdqZV53uiQE",

"CgACAgQAAxkBAAIMuGKkwUpO-1cS5jFtKVCwoBBHUM6KAAIwBwACSHDoUvWimLWKVaPmJAQ",

"CgACAgUAAxkBAAIMu2KkwVwwO22OcIeXRkkAAVdqlGbehwACxgIAApmJKVRLUlxoNIFZEyQE",

"CgACAgEAAxkBAAIMvmKkwYnk_0TU-WirJmc7VdRrf9L2AALjAQACK3GRRG7Q3paUfPCTJAQ",

"CgACAgQAAxkBAAIMwWKkwZxBpAdjUV59UPRrhgwTaUnTAAIoCQACyYChUPW0_OmhT-dOJAQ",

"CgACAgQAAxkBAAIMxGKkwcraVtVgKi9HDNWjgXEfNPNsAAI9CAAC_nzoULs66uak0y54JAQ",

"CgACAgQAAxkBAAIMx2Kkwdw9Z_je48UWB-KOR77BGi-AAAIlDAACYYIRUnHH35WicZ-7JAQ",

"CgACAgQAAxkBAAIMymKkwfVsViDhpsue1CLJe0oa-iGQAAJBCAACA5mQUjeNSk71QCXzJAQ",

"CgACAgQAAxkBAAIMzWKkwgeNjgsw3_lcjQRT80Ym130hAAI9CQACiY2pUjgXn14p7LrYJAQ",

"CgACAgEAAxkBAAIM0GKkwh1zF8sVKgABcSltj0VzvT1IQgACnwEAAgQ-MUTsqsesSHHuWCQE",

"CgACAgQAAxkBAAIM02KkwkCWvoezynixAkvd2ulTlsdDAAJIAwACfL1_B2iitkosDVg7JAQ",

"CgACAgQAAxkBAAIM1mKkwlV1cYsDOyam5gnBxQHRhMOBAAI1BwACGExpU3CKtvTwIgjwJAQ",

"CgACAgUAAxkBAAIM2WKkwmdeIGUoOfaHX_HeFFLBoSucAAKLAgACcXdhVs9rdylgigbQJAQ",

"CgACAgQAAx0CZ0OYtQADVGKkw4N4xXDJmJofsa4oG4lc5aT6AAIlDAACYYIRUnHH35WicZ-7JAQ",

"CgACAgIAAx0CZ0OYtQADVWKkw4NLTHltvOK-KaSJTkjsCiiWAALIAwAC7X3YShvP9EEXpc1KJAQ",

"CgACAgQAAx0CZ0OYtQADXGKkw4OnyHVAx4D-EvGa5pSH6xf8AAKFAgACgFq1UfyDnm4Cr6SoJAQ",

"CgACAgUAAx0CZ0OYtQADXWKkw4NLCr1wkY4OcYI99OQSdF-lAAKEBAACsYW4VD5yZnD_UXkAASQE",

"CgACAgQAAx0CZ0OYtQADXmKkw4MIXtVBIfn9kkw1kjCplk5mAAJOAgACdtN9UN1tuhcPmOhpJAQ",

"CgACAgUAAx0CZ0OYtQADX2Kkw4NU3ksKJINRYcGc5TxeDIvaAAIzBQACTORAVq2xscEm0vhIJAQ",

"CgACAgQAAx0CZ0OYtQADYGKkw4MxscJRt2NltnUJC-L_Lz-jAAJWBwACKUn5UER8Oc82sIHyJAQ",

"CgACAgQAAx0CZ0OYtQADYWKkw4MNEavIb3UfQUL5hYWk4-cVAAIFCQACaPH4U3H6blRPTuNcJAQ",

"CgACAgQAAx0CZ0OYtQADYmKkw4MvXHmKAw4EuGx-BTeUv5ZfAAIRCQACqz7BUUTXqxHDXu29JAQ",

"CgACAgQAAx0CZ0OYtQADY2Kkw4OPqDRtwAbrMbvZRNsKxHkdAAIpDAACHZ6JUfhA52plXne6JAQ",

"CgACAgQAAx0CZ0OYtQADZGKkw4NlaxEQZIh7cedSAvgo-wemAAL3CgACFqvZUOpIfayIJ646JAQ",

"CgACAgQAAxkBAAIMEWKku4V8Gk6mJSj3F0bg5vsN21tBAAIVAwACwguFUZRMHnDmBR_vJAQ",


"CgACAgQAAxkBAAIMEmKku4WOzT9Y9Oz2czaiVdnFFV7QAAJ1AgACYFeMUpQFz5UitARhJAQ",


"CgACAgQAAxkBAAIME2Kku4WYGcgexCN6_Du3rYbFfUl5AAJeCgAC5jl4UPYi6aP7L0BYJAQ",


"CgACAgQAAxkBAAIMFGKku4U91Bkgfia5xyx3798w1x1FAAK4CQACU0IxUiwKDYvOwe_jJAQ",


"CgACAgQAAxkBAAIMFWKku4VUeCgSL1lWP09ZQ6W0NSR_AALEAgACW2okUMNiKzhSIDu1JAQ",


"CgACAgQAAxkBAAIMFmKku4XKG585aJW3CMK0IwIlrNZEAAIQAgACMldlUxZE4Jh5veeHJAQ",


"CgACAgQAAxkBAAIMF2Kku4VkeUOLgB6jrJmKAn8eh6mzAALNAgACz5ipUbFuY9IPqvwbJAQ",


"CgACAgUAAxkBAAIMGGKku4WjTvyN0V0CqneOPeFfAcy7AALQAQACMDnQVR6h0xH8fNn3JAQ",


"CgACAgIAAxkBAAIMGWKku4XGxoFnlSAAAUUh2S_gSElJxwACBwcAAtndWUqLJJqQ7eBXUCQE",


"CgACAgUAAxkBAAIMGmKku4WYusmJQ1rQEcHrOQTbEKafAALjAAPJeGFWTD6H-kdP6q4kBA",


"CgACAgQAAxkBAAIMG2Kku4UPAuSbNm-AgjpdZBs5Jn5cAAI6AgACiXCFUi8soQU7JN2vJAQ",

"CgACAgIAAxkBAAIMHGKku4X2ZagXApEDzP0MQd34QwTzAAK1AwACv9vwSVjEUKt5z9zgJAQ",


"CgACAgIAAxkBAAIMHWKku4VpsPG0LjrCOQIAAfwtITY8GQACcwUAAi0LAUsfMyE9jNzieSQE",


"CgACAgQAAxkBAAIMHmKku4W4Z3IsqfviuCO4zHT5NuhwAAJGAgAC4959U_iNIGAJRierJAQ",


"CgACAgQAAxkBAAIMH2Kku4WSmi3bTg70hNMYHJfKiqBhAAIUAgACm-GMUu4oJqcAAbU7lSQE",


"CgACAgQAAxkBAAIMIGKku4V8lknUlfbZIlrlP3TfyfkZAALPAgAC-yF1UkjgtatV4isjJAQ",


"CgACAgQAAxkBAAIMIWKku4W7-5mrfLKl3jCmJUv8awGTAAIoAgAChL2VUnxD_xS4d87CJAQ",

"CgACAgQAAxkBAAIMImKku4Xd7P5HcVsAAVZAeuApVLvzCAAC7wYAAi69SVPEjfXx_1UTqCQE",

"CgACAgQAAxkBAAIMI2Kku4WWxZPaDND3nLqD_hUAAQ3w7wACPQMAApZEFFGmMrzOkas1AAEkBA",

"CgACAgQAAxkBAAIMI2Kku4WWxZPaDND3nLqD_hUAAQ3w7wACPQMAApZEFFGmMrzOkas1AAEkBA"
       
 ]


NEKO_TEXT = [

     "@NekoArsh, the Neko, Scratches you!",

     "Nya! {user1} is a Neko!",

     "My Heart Goes Meow😻",

     "Neko Neko Niii!"

     "{user1} nyaed {user2}"

   ]

CATTO_GIFS = [

    "CgACAgEAAxkBAAIMqWKkwJl_fnKO6mJTiQVgKj0SS41vAAKfAQACBD4xROyqx6xIce5YJAQ",

"CgACAgQAAxkBAAIMrGKkwMB_blD-bNvnheVCEgQSf_ncAAJWBwACKUn5UER8Oc82sIHyJAQ",

"CgACAgQAAxkBAAIMr2KkwPtvMAwMQr7aiZVC5vQSMphcAAIFCQACaPH4U3H6blRPTuNcJAQ",

"CgACAgQAAxkBAAIMsmKkwREX5mjlpb_Y7TcukoFVFqF5AAIRCQACqz7BUUTXqxHDXu29JAQ",

"CgACAgQAAxkBAAIMtWKkwSpbTQAB7dO7rX2aUThycvHLZgACKQwAAh2eiVH4QOdqZV53uiQE",

"CgACAgQAAxkBAAIMuGKkwUpO-1cS5jFtKVCwoBBHUM6KAAIwBwACSHDoUvWimLWKVaPmJAQ",

"CgACAgUAAxkBAAIMu2KkwVwwO22OcIeXRkkAAVdqlGbehwACxgIAApmJKVRLUlxoNIFZEyQE",

"CgACAgEAAxkBAAIMvmKkwYnk_0TU-WirJmc7VdRrf9L2AALjAQACK3GRRG7Q3paUfPCTJAQ",

"CgACAgQAAxkBAAIMwWKkwZxBpAdjUV59UPRrhgwTaUnTAAIoCQACyYChUPW0_OmhT-dOJAQ",

"CgACAgQAAxkBAAIMxGKkwcraVtVgKi9HDNWjgXEfNPNsAAI9CAAC_nzoULs66uak0y54JAQ",

"CgACAgQAAxkBAAIMx2Kkwdw9Z_je48UWB-KOR77BGi-AAAIlDAACYYIRUnHH35WicZ-7JAQ",

"CgACAgQAAxkBAAIMymKkwfVsViDhpsue1CLJe0oa-iGQAAJBCAACA5mQUjeNSk71QCXzJAQ",

"CgACAgQAAxkBAAIMzWKkwgeNjgsw3_lcjQRT80Ym130hAAI9CQACiY2pUjgXn14p7LrYJAQ",

"CgACAgEAAxkBAAIM0GKkwh1zF8sVKgABcSltj0VzvT1IQgACnwEAAgQ-MUTsqsesSHHuWCQE",

"CgACAgQAAxkBAAIM02KkwkCWvoezynixAkvd2ulTlsdDAAJIAwACfL1_B2iitkosDVg7JAQ",

"CgACAgQAAxkBAAIM1mKkwlV1cYsDOyam5gnBxQHRhMOBAAI1BwACGExpU3CKtvTwIgjwJAQ",

"CgACAgUAAxkBAAIM2WKkwmdeIGUoOfaHX_HeFFLBoSucAAKLAgACcXdhVs9rdylgigbQJAQ",

"CgACAgQAAx0CZ0OYtQADVGKkw4N4xXDJmJofsa4oG4lc5aT6AAIlDAACYYIRUnHH35WicZ-7JAQ",

"CgACAgIAAx0CZ0OYtQADVWKkw4NLTHltvOK-KaSJTkjsCiiWAALIAwAC7X3YShvP9EEXpc1KJAQ",

"CgACAgQAAx0CZ0OYtQADXGKkw4OnyHVAx4D-EvGa5pSH6xf8AAKFAgACgFq1UfyDnm4Cr6SoJAQ",

"CgACAgUAAx0CZ0OYtQADXWKkw4NLCr1wkY4OcYI99OQSdF-lAAKEBAACsYW4VD5yZnD_UXkAASQE",

"CgACAgQAAx0CZ0OYtQADXmKkw4MIXtVBIfn9kkw1kjCplk5mAAJOAgACdtN9UN1tuhcPmOhpJAQ",

"CgACAgUAAx0CZ0OYtQADX2Kkw4NU3ksKJINRYcGc5TxeDIvaAAIzBQACTORAVq2xscEm0vhIJAQ",

"CgACAgQAAx0CZ0OYtQADYGKkw4MxscJRt2NltnUJC-L_Lz-jAAJWBwACKUn5UER8Oc82sIHyJAQ",

"CgACAgQAAx0CZ0OYtQADYWKkw4MNEavIb3UfQUL5hYWk4-cVAAIFCQACaPH4U3H6blRPTuNcJAQ",

"CgACAgQAAx0CZ0OYtQADYmKkw4MvXHmKAw4EuGx-BTeUv5ZfAAIRCQACqz7BUUTXqxHDXu29JAQ",

"CgACAgQAAx0CZ0OYtQADY2Kkw4OPqDRtwAbrMbvZRNsKxHkdAAIpDAACHZ6JUfhA52plXne6JAQ",

"CgACAgQAAx0CZ0OYtQADZGKkw4NlaxEQZIh7cedSAvgo-wemAAL3CgACFqvZUOpIfayIJ646JAQ",

"CgACAgQAAxkBAAIMEWKku4V8Gk6mJSj3F0bg5vsN21tBAAIVAwACwguFUZRMHnDmBR_vJAQ",


"CgACAgQAAxkBAAIMEmKku4WOzT9Y9Oz2czaiVdnFFV7QAAJ1AgACYFeMUpQFz5UitARhJAQ",


"CgACAgQAAxkBAAIME2Kku4WYGcgexCN6_Du3rYbFfUl5AAJeCgAC5jl4UPYi6aP7L0BYJAQ",


"CgACAgQAAxkBAAIMFGKku4U91Bkgfia5xyx3798w1x1FAAK4CQACU0IxUiwKDYvOwe_jJAQ",


"CgACAgQAAxkBAAIMFWKku4VUeCgSL1lWP09ZQ6W0NSR_AALEAgACW2okUMNiKzhSIDu1JAQ",


"CgACAgQAAxkBAAIMFmKku4XKG585aJW3CMK0IwIlrNZEAAIQAgACMldlUxZE4Jh5veeHJAQ",


"CgACAgQAAxkBAAIMF2Kku4VkeUOLgB6jrJmKAn8eh6mzAALNAgACz5ipUbFuY9IPqvwbJAQ",


"CgACAgUAAxkBAAIMGGKku4WjTvyN0V0CqneOPeFfAcy7AALQAQACMDnQVR6h0xH8fNn3JAQ",


"CgACAgIAAxkBAAIMGWKku4XGxoFnlSAAAUUh2S_gSElJxwACBwcAAtndWUqLJJqQ7eBXUCQE",


"CgACAgUAAxkBAAIMGmKku4WYusmJQ1rQEcHrOQTbEKafAALjAAPJeGFWTD6H-kdP6q4kBA",


"CgACAgQAAxkBAAIMG2Kku4UPAuSbNm-AgjpdZBs5Jn5cAAI6AgACiXCFUi8soQU7JN2vJAQ",

"CgACAgIAAxkBAAIMHGKku4X2ZagXApEDzP0MQd34QwTzAAK1AwACv9vwSVjEUKt5z9zgJAQ",


"CgACAgIAAxkBAAIMHWKku4VpsPG0LjrCOQIAAfwtITY8GQACcwUAAi0LAUsfMyE9jNzieSQE",


"CgACAgQAAxkBAAIMHmKku4W4Z3IsqfviuCO4zHT5NuhwAAJGAgAC4959U_iNIGAJRierJAQ",


"CgACAgQAAxkBAAIMH2Kku4WSmi3bTg70hNMYHJfKiqBhAAIUAgACm-GMUu4oJqcAAbU7lSQE",


"CgACAgQAAxkBAAIMIGKku4V8lknUlfbZIlrlP3TfyfkZAALPAgAC-yF1UkjgtatV4isjJAQ",


"CgACAgQAAxkBAAIMIWKku4W7-5mrfLKl3jCmJUv8awGTAAIoAgAChL2VUnxD_xS4d87CJAQ",

"CgACAgQAAxkBAAIMImKku4Xd7P5HcVsAAVZAeuApVLvzCAAC7wYAAi69SVPEjfXx_1UTqCQE",

"CgACAgQAAxkBAAIMI2Kku4WWxZPaDND3nLqD_hUAAQ3w7wACPQMAApZEFFGmMrzOkas1AAEkBA",

"CgACAgQAAxkBAAIMI2Kku4WWxZPaDND3nLqD_hUAAQ3w7wACPQMAApZEFFGmMrzOkas1AAEkBA"
       
       

      ]

CATTO_TEXT = [

      "Cat Is Sleeping Nya!",

      "Catto Just Scratched you",

      "@NekoArsh is the Catto Lord",

      "Catto is playing with @DushmanXRONIN now!",

      "Catto Loves You ❤"

    ]
